title: Kabir Raj Singh — Blog
description: Mirror of my Medium posts
url: "https://blog.kabirrajsingh.com"
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
